language: objective-c
before_install:
- brew update
- brew upgrade cmake
- brew install android-sdk ant
- echo y | android update sdk --no-ui --all --filter "platform-tools,build-tools-21.1.2,android-21"
- travis_wait brew install android-ndk
script:
- (cd android && android update project -p . --target android-21 && ndk-build && ant debug)
- (cd ios && xcodebuild -project ../SDL/Xcode-iOS/SDL/SDL.xcodeproj && xcodebuild  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project nativesdldemo.xcodeproj)
- (cd desktop && cmake . && make)
cache:
  directories:
  - /Library/Caches/Homebrew
