language: objective-c
before_install:
  - brew update
  - brew install android-ndk
script:
  - (cd android && ndk-build)
  - (cd ios && xcodebuild -project ../SDL/Xcode-iOS/SDL/SDL.xcodeproj && xcodebuild -project nativesdldemo.xcodeproj)
  - (cd desktop && cmake . && make)
