language: objective-c
before_install:
  - brew update
  - brew install android-ndk
script:
  - (cd android && ndk-build)
  - (cd ios && xcodebuild nativesdldemo.xcodeproj)
  - (cd desktop && cmake . && make)
