language: objective-c
before_install:
  - brew update
  - brew install android-ndk
  - brew install ant
script:
  - (cd android && ndk-build && ant debug)
  - (cd ios && xcodebuild -project ../SDL/Xcode-iOS/SDL/SDL.xcodeproj && xcodebuild  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -project nativesdldemo.xcodeproj)
  - (cd desktop && cmake . && make)
